language: php
dist: trusty


php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer install --no-interaction --prefer-source

# vim:ts=2:sw=2:et
