language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer install --optimize-autoloader

script:
  - ./vendor/bin/phpcs -n -p --standard=PSR12 ./src ./tests ./*.php ./bin
  - ./vendor/bin/phpunit

# vim:ts=2:sw=2:et
